### ISSUE TITLE
Consider allowing "dsCMatrix" as well as "dgCMatrix"

### ISSUE THREAD

**Issue by aadler** [braunm/trustOptim#1]
The Matrix package also defines a sparse symmetric matrix type ""dsCMatrix", for which only the upper triangle needs to be passed. As all Hessians are _ipso facto_ symmetric, can this option be added to the package too?

**Comment by braunm** [comment]
It's been a long time since I've looked, but I think there was an issue between converting an R symmetric sparse matrix to an Eigen symmetric sparse matrix.  If I recall correctly, there is/was no constructor in Eigen, so I would have had to write the conversion process myself.  And since it's really easy to convert a dsCMatrix to a dgCMatrix, it made more sense to let the user do it.

Of course, I am open to pull requests.

**Comment by aadler** [comment]
I didn't realize that a special constructor had to be built; yes, it is probably not worth the effort given that it is almost identical to building the non-symmetric. It would need to be one humongous matrix for the space savings of just having the upper/lower triangle matter. Thanks for the quick response.
